### ISSUE TITLE
Container

### ISSUE THREAD

**Issue by arunbi** [thinoo-v2/upleat-ui#3]

**Comment by thinoo-v2** [comment]
@arunbi @ryuzuka 

컴포넌트 설계를 해야합니다. 이를 위해 아래 사이트 참고해주세요

https://mantine.dev/core/container/
https://www.chakra-ui.com/docs/components/container

**Comment by arunbi** [comment]
### Example 1 - Default Container

반응형 고정너비 컨테이너로 각 breakpoint에서 max-width의 넓이가 변경.
breakpoint 예시 ) sm, md, lg, xl, xxl

```
Default Container
내용 추가 예정
```

### Example 2 - Responsive Containers

지정 된 breakpoint에 도달할 때 까지 100%의 넓이를 가지는 컨테이너.
breakpoint트 도달 시 각 사이즈 별로 지정된 max-width 값을 적용.

```
Responsive Containers
내용 추가 예정
```




### Example 3 - Fluid Container

항상 부모 요소의 100%의 넓이를 가지는 컨테이너

```
Fluid Container
내용 추가 예정
```
